#!/bin/bash

if [ -z "$1" ]; then
    echo "No argument(s) supplied. Please specify game session you want to join or make."
else
    ./run chess -s mst-ai.xyz -i 0 -n whiteBot -r "$@" &
    ./run chess -s mst-ai.xyz -i 1 -n blackBot -r "$@" &
    wait
fi
